'use strict';
// Runs the REAL analysis pipeline against a repository and writes a markdown
// evidence file. Usage: node scripts/demo.js <url-or-path> [outFile]
const fs = require('fs');
const path = require('path');
const { openDatabase } = require('../src/db/database');
const svc = require('../src/services/analysisService');
const dao = require('../src/db/dao');

(async () => {
  const url = process.argv[2];
  const out = process.argv[3] || path.join(__dirname, '..', '..', 'docs', 'DEMO_RESULTS.md');
  const allowLocal = !/^https?:\/\//.test(url);
  const db = openDatabase(':memory:');
  const t0 = Date.now();
  const { snapshotId } = await svc.analyzeRepository(db, { url }, { allowLocal });
  const elapsed = ((Date.now() - t0) / 1000).toFixed(1);
  const snap = dao.getSnapshot(db, snapshotId);

  const churn = svc.getChurn(db, snapshotId, { windowDays: null }).slice(0, 10);
  const hot = svc.getHotspots(db, snapshotId, { windowDays: null }).slice(0, 10);
  const { pairs } = svc.getCoupling(db, snapshotId, { minSharedCommits: 5 });
  const own = svc.getOwnership(db, snapshotId, {});
  const single = own.files.filter((f) => f.classification === 'single-owner').length;
  const abandoned = own.files.filter((f) => f.classification === 'abandoned').length;

  const tbl = (head, rows) => `| ${head.join(' | ')} |\n| ${head.map(() => '---').join(' | ')} |\n` +
    rows.map((r) => `| ${r.join(' | ')} |`).join('\n');

  const md = `# Codegraph — Live Demo Results

**Target repository:** ${url}
**Analyzed:** ${new Date().toISOString()}
**Wall-clock analysis time:** ${elapsed}s
**Commits analyzed:** ${snap.commit_count} · **Files:** ${snap.file_count} · **Contributors:** ${own.authors.length}

> Generated by running the actual Codegraph pipeline (clone → git log → parse → store → analyze).

## Top 10 hotspots (change frequency × size)
${tbl(['Rank', 'File', 'Commits', 'LOC', 'Score', 'Norm'],
  hot.map((h, i) => [i + 1, h.filePath, h.changeFrequency, h.loc, h.score, h.normalizedScore]))}

## Top 10 by churn (commits)
${tbl(['File', 'Commits', '+Lines', '-Lines', 'Net'],
  churn.map((c) => [c.filePath, c.commits, c.linesAdded, c.linesRemoved, c.netChange]))}

## Strongest temporal couplings (≥5 shared commits)
${tbl(['File A', 'File B', 'Shared', 'Strength'],
  pairs.slice(0, 10).map((p) => [p.fileA, p.fileB, p.sharedCommits, p.strength]))}

## Ownership risk
- Single-owner files (bus factor = 1): **${single}**
- Abandoned files (no recent activity): **${abandoned}**
- Top contributors: ${own.authors.slice(0, 5).map((a) => `${a.name || a.author} (${a.commits})`).join(', ')}
`;
  fs.writeFileSync(out, md);
  console.log(`commits=${snap.commit_count} files=${snap.file_count} contributors=${own.authors.length} time=${elapsed}s`);
  console.log(`hotspot#1=${hot[0] ? hot[0].filePath : 'n/a'} couplings=${pairs.length} single=${single} abandoned=${abandoned}`);
  console.log('wrote', out);
})().catch((e) => { console.error('DEMO FAILED:', e.message); process.exit(1); });
